### ISSUE TITLE
The onEvent function is not triggered

### ISSUE THREAD

**Issue by rogs-lv** [leyan95/pda_scanner#2]
## 
Hi, I have imported the pda_listener.dar & pda_source.dart files, but when I run mi application in debug mode and use print() sentences in order to track the execution order, the onEvent event is not triggered.

After to finish the execution, the next message appears:
	I/PdaScannerPlugin(17438): PdaScannerPlugin:onCancel
	
**Also I have test with the example posted in git with the same results.**

I'm working with a Honeywell - EDA50 - SO Android 7.1.1 device.

Do I need to configure something particular in the device or do you think that I missing something?

**Comment by wu9007** [comment]
your widget state need extends `PdaListenerState` as follow:
```dart
class PageAlphaState extends PdaListenerState<PageAlpha>{}
```

**Comment by rogs-lv** [comment]
I share part of the code I am using:

**main.dart :**


`import 'package:flutter/material.dart';
import 'package:pda_scanner/pda_source.dart';
import 'page_alpha.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    /// You need to initialize it as necessary, when the program starts for the first time.
    PdaSource.init();
  }

  @override
  void dispose() {
    super.dispose();
    /// You need to call this method to release resources when you exit the entire application.
    PdaSource.uninstall();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: PageAlpha(),
    );
  }
}`

**page_alpha.dart :**

`
import 'package:flutter/material.dart';
import 'package:pda_scanner/pda_listener.dart';
import 'page_beta.dart';

class PageAlpha extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => PageAlphaState();
}

class PageAlphaState extends PdaListenerState<PageAlpha> {
  var _code;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('PageAlpha'),
      ),
      body: Column(
        children: <Widget>[
          Text('Scanning result: $_code\n'),
          RaisedButton(
            child: Text('Got to Beta'),
            onPressed: () => Navigator.of(context).push(MaterialPageRoute(builder: (context) => PageBeta())),
          ),
        ],
      ),
    );
  }

  @override
  void onEvent(Object event) {
    setState(() {
      _code = event;
      print("ChannelPage: $event");
    });
  }
}
`

In the application doesn’t show any error. Just look like the onEvent function isn’t triggered

Thanks for answering me

**Comment by wu9007** [comment]
@OliverRG  my pleasure <br/>
    could you show me the value of broadcast name in developer options of your device.
    Does the following include the broadcast name of your device?

    com.android.server.scannerservice.broadcast
    android.intent.action.SCANRESULT
    android.intent.ACTION_DECODE_DATA
    com.ehsy.warehouse.action.BARCODE_DATA

If not, please give me the value and I will support it in the next release

**Comment by wu9007** [comment]
@OliverRG  Upgrade to 0.2.3 and try again.

**Comment by rogs-lv** [comment]
ok, I'll try the version 0.2.3 . Thanks

**Comment by rogs-lv** [comment]
I updated, cleaned the solution and rebuilt the application with version 0.2.3, but even with this, I can't get to trigger the event.
About the "broadcast name"; I'm not sure to be clear about, Could you give me more details about what do you mean or where should I take this information? I have noticed that some models haven't the same options or configurations that I need.

**Comment by wu9007** [comment]
@OliverRG Generally, there is a scan tool in the PDA device. You can set the name of the broadcast in the developer option of the scan tool, which will be monitored by the device as an identifier. Could you show me the identifier.

**Comment by mhsnprvr** [comment]
example code is not working with my urovo device
and seems like onevent isn't triggered
is this a bug or should i add some additional config?

**Comment by wu9007** [comment]
#4

**Comment by MohamedYousof** [comment]
example code is not working with me on Honeywell CT60 
the events onEvent and onError are not triggered

**Comment by jasnicaa** [comment]
not triggering onEvent with Honeywell EDA51.
